In [3]:
import pandas as pd

df = pd.read_excel('Scan File.xls')
df

,Barcode Number,Source,Room,Federal?,Description,Manufacturer,Model Number,Serial Number,Cost Center,COST,Date Acquired,Funding Code,PO Number
0,11944,TipWeb,223,YES,ASUS CHROMEBOX CN60,ASUS,CHROMEBOX CN60,E4MSCX011443,High School West,1100.0,NaN,6001.0,23-5432
1,8010,TipWeb,LOBBY,NaN,CRES COR C0151FPWUA12B2083Q1,CRES COR,C0151FPWUA12B2083Q1,EAJ-J203747-044,High School West,1458.0,2009-08-01,5101.0,FF-2234
2,2330,NextGen,CAFE,NaN,CUP DISPENSER,HOBART,CTC2X2-5,NaN,Elementary School,385.0,2004-07-23,5101.0,510307
3,3715,NextGen,602,NaN,COMPUTER TOWER,HP,360X,00045-571-601-835,Elementary School,693.0,2011-02-22,0.0,NaN
4,11762,NaN,107,YES,Laptop,lenovo,100e,CD5294G9T,Middle School,NaN,NaN,NaN,NaN
5,12667,NaN,208,NaN,Smartboard,Viewsonic,VS 15057,VS812847203,Elementary School,NaN,NaN,NaN,NaN

In [10]:
test = df.loc[:, 'Source']
test

0     TipWeb
1     TipWeb
2    NextGen
3    NextGen
4        NaN
5        NaN
Name: Source, dtype: object